apiVersion: v1
kind: Secret
metadata:
  name: k3s-manager
  namespace: kube-system
  labels:
    app: k3s-manager
    name: {{ .Config.Name | quote }}
data:
  config: {{ .Config | toYaml | b64enc | quote }}
  joinToken: {{ .JoinToken | b64enc | quote }}
  {{- range $key, $value := .ProviderSecrets }}
  {{ $key | quote }}: {{ $value | b64enc | quote }}
  {{- end }}
