apiVersion: v1
kind: Secret
metadata:
  name: hcloud
  namespace: kube-system
  labels:
    app: k3s-manager
    provider: hetzner
    name: hcloud
data:
  token: {{ .Config.Token | b64enc | quote }}
